-- Acid 0.1.0 — Citric, for Neovim
--
-- Generated by acidify from ports/neovim/acid.lua.tera. Do not edit; edit the
-- template, or the palette in crates/acid-palette/src/lib.rs, and re-run
-- `make ports`.
--
-- Accents follow the role table in docs/PALETTE.md rather than gruvbox's own
-- mapping: keywords are purple and functions aqua, which keeps red for things
-- that are actually wrong. Exceptions are the exception — they stay red.

local p = {
  red = "#de5a48",
  orange = "#dd7b34",
  yellow = "#d9a441",
  green = "#a3ab2f",
  aqua = "#7cad76",
  blue = "#7d9cba",
  purple = "#c5839c",
  text = "#e2d6b6",
  subtext1 = "#cabea7",
  subtext0 = "#b4ab9b",
  overlay2 = "#9f988a",
  overlay1 = "#857d70",
  overlay0 = "#6b665c",
  surface2 = "#5b554a",
  surface1 = "#49443b",
  surface0 = "#35332c",
  base = "#1c1b19",
  mantle = "#121211",
  crust = "#060605",
  none = "NONE",
}

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "acid-citric"
vim.o.termguicolors = true
vim.o.background = "dark"

local groups = {
  -- Editor
  Normal = { fg = p.text, bg = p.base },
  NormalNC = { fg = p.text, bg = p.base },
  -- Floats sit above the editor field in both flavours, so they use a surface
  -- rather than mantle, whose direction depends on the flavour's depth axis.
  NormalFloat = { fg = p.text, bg = p.surface0 },
  FloatBorder = { fg = p.surface2, bg = p.surface0 },
  FloatTitle = { fg = p.yellow, bg = p.surface0, bold = true },
  Cursor = { fg = p.base, bg = p.yellow },
  lCursor = { fg = p.base, bg = p.yellow },
  CursorIM = { fg = p.base, bg = p.yellow },
  TermCursor = { fg = p.base, bg = p.aqua },
  CursorLine = { bg = p.surface0 },
  CursorColumn = { bg = p.surface0 },
  CursorLineNr = { fg = p.yellow, bold = true },
  LineNr = { fg = p.overlay0 },
  LineNrAbove = { fg = p.overlay0 },
  LineNrBelow = { fg = p.overlay0 },
  SignColumn = { fg = p.overlay0, bg = p.none },
  FoldColumn = { fg = p.overlay0, bg = p.none },
  Folded = { fg = p.overlay2, bg = p.surface0 },
  ColorColumn = { bg = p.surface0 },
  Conceal = { fg = p.overlay1 },
  NonText = { fg = p.surface2 },
  EndOfBuffer = { fg = p.surface1 },
  Whitespace = { fg = p.surface2 },
  SpecialKey = { fg = p.surface2 },
  MatchParen = { fg = p.yellow, bg = p.surface2, bold = true },
  Visual = { bg = p.surface2 },
  VisualNOS = { bg = p.surface2 },
  Search = { fg = p.base, bg = p.yellow },
  IncSearch = { fg = p.base, bg = p.orange },
  CurSearch = { fg = p.base, bg = p.orange },
  Substitute = { fg = p.base, bg = p.red },
  QuickFixLine = { bg = p.surface1, bold = true },
  Directory = { fg = p.blue },
  Title = { fg = p.yellow, bold = true },
  WinSeparator = { fg = p.surface2 },
  VertSplit = { fg = p.surface2 },

  -- Chrome. Mantle follows the flavour's depth axis: below the editor field in
  -- citric, above it in acetic, where base is already pure black.
  StatusLine = { fg = p.subtext1, bg = p.mantle },
  StatusLineNC = { fg = p.overlay0, bg = p.mantle },
  TabLine = { fg = p.overlay1, bg = p.mantle },
  TabLineSel = { fg = p.text, bg = p.surface1, bold = true },
  TabLineFill = { bg = p.crust },
  WinBar = { fg = p.subtext1, bg = p.none, bold = true },
  WinBarNC = { fg = p.overlay1, bg = p.none },

  -- Menus
  Pmenu = { fg = p.subtext1, bg = p.surface0 },
  PmenuSel = { fg = p.text, bg = p.surface2, bold = true },
  PmenuKind = { fg = p.yellow, bg = p.surface0 },
  PmenuKindSel = { fg = p.yellow, bg = p.surface2 },
  PmenuExtra = { fg = p.overlay1, bg = p.surface0 },
  PmenuExtraSel = { fg = p.subtext0, bg = p.surface2 },
  PmenuSbar = { bg = p.surface1 },
  PmenuThumb = { bg = p.overlay0 },
  PmenuMatch = { fg = p.aqua, bg = p.surface0, bold = true },
  PmenuMatchSel = { fg = p.aqua, bg = p.surface2, bold = true },
  WildMenu = { fg = p.base, bg = p.yellow },
  ComplMatchIns = { fg = p.overlay2 },

  -- Messages
  ModeMsg = { fg = p.subtext1, bold = true },
  MsgArea = { fg = p.text },
  MsgSeparator = { fg = p.surface2, bg = p.mantle },
  MoreMsg = { fg = p.aqua },
  Question = { fg = p.aqua },
  WarningMsg = { fg = p.orange },
  ErrorMsg = { fg = p.red, bold = true },
  OkMsg = { fg = p.green },
  -- Neovim's own defaults for these are off-palette greys.
  FloatShadow = { bg = p.crust, blend = 36 },
  FloatShadowThrough = { bg = p.crust, blend = 66 },

  -- Diffs. Backgrounds are the accent blended almost all the way into base, so
  -- they tint the line without competing with the text on top of it.
  DiffAdd = { bg = "#34351d" },
  DiffChange = { bg = "#2a2d30" },
  DiffDelete = { fg = p.red, bg = "#372420" },
  DiffText = { bg = "#3b444d" },
  diffAdded = { fg = p.green },
  diffRemoved = { fg = p.red },
  diffChanged = { fg = p.blue },
  diffFile = { fg = p.yellow },
  diffLine = { fg = p.overlay2 },
  diffIndexLine = { fg = p.purple },

  -- Spelling
  SpellBad = { sp = p.red, undercurl = true },
  SpellCap = { sp = p.yellow, undercurl = true },
  SpellLocal = { sp = p.aqua, undercurl = true },
  SpellRare = { sp = p.purple, undercurl = true },

  -- Legacy syntax groups. Treesitter links into these, so they carry the
  -- mapping for everything without a parser too.
  Comment = { fg = p.overlay1, italic = true },
  Constant = { fg = p.orange },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.orange },
  Boolean = { fg = p.orange },
  Float = { fg = p.orange },
  Identifier = { fg = p.blue },
  Function = { fg = p.aqua },
  Statement = { fg = p.purple },
  Conditional = { fg = p.purple },
  Repeat = { fg = p.purple },
  Label = { fg = p.purple },
  Operator = { fg = p.purple },
  Keyword = { fg = p.purple },
  Exception = { fg = p.red },
  PreProc = { fg = p.aqua },
  Include = { fg = p.aqua },
  Define = { fg = p.aqua },
  Macro = { fg = p.aqua },
  PreCondit = { fg = p.aqua },
  Type = { fg = p.yellow },
  StorageClass = { fg = p.purple },
  Structure = { fg = p.yellow },
  Typedef = { fg = p.yellow },
  Special = { fg = p.orange },
  SpecialChar = { fg = p.orange },
  Tag = { fg = p.purple },
  Delimiter = { fg = p.overlay2 },
  SpecialComment = { fg = p.overlay2, italic = true },
  Debug = { fg = p.red },
  Underlined = { fg = p.blue, underline = true },
  Ignore = { fg = p.overlay0 },
  Error = { fg = p.red },
  Todo = { fg = p.base, bg = p.yellow, bold = true },
  Added = { fg = p.green },
  Removed = { fg = p.red },
  Changed = { fg = p.blue },

  -- Treesitter
  ["@variable"] = { fg = p.text },
  ["@variable.builtin"] = { fg = p.orange, italic = true },
  ["@variable.parameter"] = { fg = p.blue },
  ["@variable.parameter.builtin"] = { fg = p.blue, italic = true },
  ["@variable.member"] = { fg = p.blue },
  ["@constant"] = { fg = p.orange },
  ["@constant.builtin"] = { fg = p.orange, italic = true },
  ["@constant.macro"] = { fg = p.aqua },
  ["@module"] = { fg = p.yellow },
  ["@module.builtin"] = { fg = p.yellow, italic = true },
  ["@label"] = { fg = p.purple },
  ["@string"] = { fg = p.green },
  ["@string.documentation"] = { fg = p.green, italic = true },
  ["@string.regexp"] = { fg = p.aqua },
  ["@string.escape"] = { fg = p.orange },
  ["@string.special"] = { fg = p.orange },
  ["@string.special.url"] = { fg = p.blue, underline = true },
  ["@character"] = { fg = p.green },
  ["@character.special"] = { fg = p.orange },
  ["@boolean"] = { fg = p.orange },
  ["@number"] = { fg = p.orange },
  ["@number.float"] = { fg = p.orange },
  ["@type"] = { fg = p.yellow },
  ["@type.builtin"] = { fg = p.yellow, italic = true },
  ["@type.definition"] = { fg = p.yellow },
  ["@attribute"] = { fg = p.orange },
  ["@attribute.builtin"] = { fg = p.orange, italic = true },
  ["@property"] = { fg = p.blue },
  ["@function"] = { fg = p.aqua },
  ["@function.builtin"] = { fg = p.aqua, italic = true },
  ["@function.call"] = { fg = p.aqua },
  ["@function.macro"] = { fg = p.aqua },
  ["@function.method"] = { fg = p.aqua },
  ["@function.method.call"] = { fg = p.aqua },
  ["@constructor"] = { fg = p.yellow },
  ["@operator"] = { fg = p.purple },
  ["@keyword"] = { fg = p.purple },
  ["@keyword.coroutine"] = { fg = p.purple },
  ["@keyword.function"] = { fg = p.purple },
  ["@keyword.operator"] = { fg = p.purple },
  ["@keyword.import"] = { fg = p.aqua },
  ["@keyword.type"] = { fg = p.purple },
  ["@keyword.modifier"] = { fg = p.purple },
  ["@keyword.repeat"] = { fg = p.purple },
  ["@keyword.return"] = { fg = p.purple },
  ["@keyword.debug"] = { fg = p.red },
  ["@keyword.exception"] = { fg = p.red },
  ["@keyword.conditional"] = { fg = p.purple },
  ["@keyword.directive"] = { fg = p.aqua },
  ["@punctuation.delimiter"] = { fg = p.overlay2 },
  ["@punctuation.bracket"] = { fg = p.subtext0 },
  ["@punctuation.special"] = { fg = p.purple },
  ["@comment"] = { fg = p.overlay1, italic = true },
  ["@comment.documentation"] = { fg = p.overlay2, italic = true },
  ["@comment.error"] = { fg = p.base, bg = p.red, bold = true },
  ["@comment.warning"] = { fg = p.base, bg = p.orange, bold = true },
  ["@comment.todo"] = { fg = p.base, bg = p.yellow, bold = true },
  ["@comment.note"] = { fg = p.base, bg = p.aqua, bold = true },
  ["@tag"] = { fg = p.purple },
  ["@tag.builtin"] = { fg = p.purple },
  ["@tag.attribute"] = { fg = p.yellow },
  ["@tag.delimiter"] = { fg = p.overlay2 },
  ["@diff.plus"] = { fg = p.green },
  ["@diff.minus"] = { fg = p.red },
  ["@diff.delta"] = { fg = p.blue },

  -- Markup
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = p.yellow, bold = true },
  ["@markup.heading.1"] = { fg = p.yellow, bold = true },
  ["@markup.heading.2"] = { fg = p.orange, bold = true },
  ["@markup.heading.3"] = { fg = p.green, bold = true },
  ["@markup.heading.4"] = { fg = p.aqua, bold = true },
  ["@markup.heading.5"] = { fg = p.blue, bold = true },
  ["@markup.heading.6"] = { fg = p.purple, bold = true },
  ["@markup.quote"] = { fg = p.overlay2, italic = true },
  ["@markup.math"] = { fg = p.aqua },
  ["@markup.link"] = { fg = p.blue },
  ["@markup.link.label"] = { fg = p.aqua },
  ["@markup.link.url"] = { fg = p.blue, underline = true },
  ["@markup.raw"] = { fg = p.green },
  ["@markup.raw.block"] = { fg = p.subtext1 },
  ["@markup.list"] = { fg = p.purple },
  ["@markup.list.checked"] = { fg = p.green },
  ["@markup.list.unchecked"] = { fg = p.overlay2 },

  -- Diagnostics
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.orange },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.aqua },
  DiagnosticOk = { fg = p.green },
  DiagnosticVirtualTextError = { fg = p.red, bg = "#33231f" },
  DiagnosticVirtualTextWarn = { fg = p.orange, bg = "#33271c" },
  DiagnosticVirtualTextInfo = { fg = p.blue, bg = "#282a2c" },
  DiagnosticVirtualTextHint = { fg = p.aqua, bg = "#282d24" },
  DiagnosticVirtualTextOk = { fg = p.green, bg = "#2c2c1c" },
  DiagnosticUnderlineError = { sp = p.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.aqua, undercurl = true },
  DiagnosticUnderlineOk = { sp = p.green, undercurl = true },
  DiagnosticDeprecated = { sp = p.overlay2, strikethrough = true },
  DiagnosticUnnecessary = { fg = p.overlay1 },

  -- LSP
  LspReferenceText = { bg = p.surface1 },
  LspReferenceRead = { bg = p.surface1 },
  LspReferenceWrite = { bg = p.surface1, bold = true },
  LspReferenceTarget = { bg = p.surface1 },
  LspSignatureActiveParameter = { fg = p.yellow, bold = true },
  LspCodeLens = { fg = p.overlay1, italic = true },
  LspCodeLensSeparator = { fg = p.overlay0 },
  LspInlayHint = { fg = p.overlay1, bg = p.surface0, italic = true },
  SnippetTabstop = { bg = p.surface1 },

  -- Git signs, the one plugin whose groups are near universal.
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.blue },
  GitSignsDelete = { fg = p.red },
  GitSignsUntracked = { fg = p.overlay1 },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end

-- Semantic tokens defer to the treesitter groups, so an LSP does not repaint a
-- buffer differently from the parser.
for from, to in pairs({
  ["@lsp.type.class"] = "@type",
  ["@lsp.type.comment"] = "@comment",
  ["@lsp.type.decorator"] = "@attribute",
  ["@lsp.type.enum"] = "@type",
  ["@lsp.type.enumMember"] = "@constant",
  ["@lsp.type.event"] = "@type",
  ["@lsp.type.function"] = "@function",
  ["@lsp.type.interface"] = "@type",
  ["@lsp.type.keyword"] = "@keyword",
  ["@lsp.type.macro"] = "@function.macro",
  ["@lsp.type.method"] = "@function.method",
  ["@lsp.type.modifier"] = "@keyword.modifier",
  ["@lsp.type.namespace"] = "@module",
  ["@lsp.type.number"] = "@number",
  ["@lsp.type.operator"] = "@operator",
  ["@lsp.type.parameter"] = "@variable.parameter",
  ["@lsp.type.property"] = "@property",
  ["@lsp.type.regexp"] = "@string.regexp",
  ["@lsp.type.string"] = "@string",
  ["@lsp.type.struct"] = "@type",
  ["@lsp.type.type"] = "@type",
  ["@lsp.type.typeParameter"] = "@type.definition",
  ["@lsp.type.variable"] = "@variable",
}) do
  vim.api.nvim_set_hl(0, from, { link = to })
end

-- The terminal palette matches the Alacritty port, so :terminal looks the same
-- as the terminal Neovim is running in.
vim.g.terminal_color_0 = p.surface1
vim.g.terminal_color_1 = p.red
vim.g.terminal_color_2 = p.green
vim.g.terminal_color_3 = p.yellow
vim.g.terminal_color_4 = p.blue
vim.g.terminal_color_5 = p.purple
vim.g.terminal_color_6 = p.aqua
vim.g.terminal_color_7 = p.subtext1
vim.g.terminal_color_8 = p.surface2
vim.g.terminal_color_9 = "#e4796b"
vim.g.terminal_color_10 = "#c0c93a"
vim.g.terminal_color_11 = "#e0b463"
vim.g.terminal_color_12 = "#98b0c8"
vim.g.terminal_color_13 = "#d29fb2"
vim.g.terminal_color_14 = "#94bc90"
vim.g.terminal_color_15 = p.text
